//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SifarisEntities : DbContext
    {
        public SifarisEntities()
            : base("name=SifarisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<tblBasaisaraiDarta> tblBasaisaraiDartas { get; set; }
        public virtual DbSet<tblBasaisaraiDartaInformant> tblBasaisaraiDartaInformants { get; set; }
        public virtual DbSet<tblBasaisaraiKaran> tblBasaisaraiKarans { get; set; }
        public virtual DbSet<tblBasaisaraiPersonalDetail> tblBasaisaraiPersonalDetails { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblEducation> tblEducations { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblFiscalYear> tblFiscalYears { get; set; }
        public virtual DbSet<tblGender> tblGenders { get; set; }
        public virtual DbSet<tblJaggaCharKillaBibaran> tblJaggaCharKillaBibarans { get; set; }
        public virtual DbSet<tblJaggaDhaniBibaran> tblJaggaDhaniBibarans { get; set; }
        public virtual DbSet<tblJaggaThaunBibaran> tblJaggaThaunBibarans { get; set; }
        public virtual DbSet<tblJanmadaMaddat> tblJanmadaMaddats { get; set; }
        public virtual DbSet<tblJanmaDarta> tblJanmaDartas { get; set; }
        public virtual DbSet<tblJanmaDartaFatherDetail> tblJanmaDartaFatherDetails { get; set; }
        public virtual DbSet<tblJanmaDartaInformant> tblJanmaDartaInformants { get; set; }
        public virtual DbSet<tblJanmaDartaMotherDetail> tblJanmaDartaMotherDetails { get; set; }
        public virtual DbSet<tblJanmaKisim> tblJanmaKisims { get; set; }
        public virtual DbSet<tblJanmaSthaan> tblJanmaSthaans { get; set; }
        public virtual DbSet<tblMrityuDarta> tblMrityuDartas { get; set; }
        public virtual DbSet<tblMrityuDartaInformant> tblMrityuDartaInformants { get; set; }
        public virtual DbSet<tblMrityuDartaPersonalDetail> tblMrityuDartaPersonalDetails { get; set; }
        public virtual DbSet<tblOccupation> tblOccupations { get; set; }
        public virtual DbSet<tblPadha> tblPadhas { get; set; }
        public virtual DbSet<tblPalika> tblPalikas { get; set; }
        public virtual DbSet<tblPanjika> tblPanjikas { get; set; }
        public virtual DbSet<tblRelation> tblRelations { get; set; }
        public virtual DbSet<tblShakha> tblShakhas { get; set; }
        public virtual DbSet<tblShreni> tblShrenis { get; set; }
        public virtual DbSet<tblSifarisType> tblSifarisTypes { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblUserProfile> tblUserProfiles { get; set; }
        public virtual DbSet<tblUserType> tblUserTypes { get; set; }
        public virtual DbSet<tblVivahBrideDetail> tblVivahBrideDetails { get; set; }
        public virtual DbSet<tblVivahDarta> tblVivahDartas { get; set; }
        public virtual DbSet<tblVivahDartaInformant> tblVivahDartaInformants { get; set; }
        public virtual DbSet<tblVivahGroomDetail> tblVivahGroomDetails { get; set; }
        public virtual DbSet<tblVivahKisim> tblVivahKisims { get; set; }
        public virtual DbSet<tblWorkOffice> tblWorkOffices { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<tblDivorceDarta> tblDivorceDartas { get; set; }
        public virtual DbSet<tblDivorceDartaInformant> tblDivorceDartaInformants { get; set; }
        public virtual DbSet<tblDivorceeHusbandDetail> tblDivorceeHusbandDetails { get; set; }
        public virtual DbSet<tblDivorceeWifeDetail> tblDivorceeWifeDetails { get; set; }
    
        public virtual ObjectResult<Nullable<System.DateTime>> sp_GetRomanDate(Nullable<int> localYear, Nullable<int> localMonth, Nullable<int> localDay)
        {
            var localYearParameter = localYear.HasValue ?
                new ObjectParameter("LocalYear", localYear) :
                new ObjectParameter("LocalYear", typeof(int));
    
            var localMonthParameter = localMonth.HasValue ?
                new ObjectParameter("LocalMonth", localMonth) :
                new ObjectParameter("LocalMonth", typeof(int));
    
            var localDayParameter = localDay.HasValue ?
                new ObjectParameter("LocalDay", localDay) :
                new ObjectParameter("LocalDay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("sp_GetRomanDate", localYearParameter, localMonthParameter, localDayParameter);
        }
    
        public virtual ObjectResult<string> sp_GetLocalDate(Nullable<System.DateTime> romanDate, Nullable<int> format)
        {
            var romanDateParameter = romanDate.HasValue ?
                new ObjectParameter("RomanDate", romanDate) :
                new ObjectParameter("RomanDate", typeof(System.DateTime));
    
            var formatParameter = format.HasValue ?
                new ObjectParameter("Format", format) :
                new ObjectParameter("Format", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetLocalDate", romanDateParameter, formatParameter);
        }
    }
}
