//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBasaisaraiDarta
    {
        public tblBasaisaraiDarta()
        {
            this.tblBasaisaraiDartaInformants = new HashSet<tblBasaisaraiDartaInformant>();
            this.tblBasaisaraiPersonalDetails = new HashSet<tblBasaisaraiPersonalDetail>();
        }
    
        public int NewMigrationId { get; set; }
        public int PanjiId { get; set; }
        public string GharMuliNaamThar { get; set; }
        public string GharMuliFullName { get; set; }
        public string BasaisaraiAayekoDartaNo { get; set; }
        public Nullable<int> BasaisaraiAayekoPradesh { get; set; }
        public Nullable<int> BasaisaraiAayekoJilla { get; set; }
        public Nullable<int> BasaisaraiAayekoPalika { get; set; }
        public Nullable<int> BasaisaraiAayekoWardNo { get; set; }
        public string BasaisaraiAayekoGharNo { get; set; }
        public string BasaisaraiAayekoGaunTole { get; set; }
        public string BasaisaraiAayekoMiti { get; set; }
        public string BasaisaraiAayekoDate { get; set; }
        public Nullable<int> BasaisaraiAayekoKaran { get; set; }
        public Nullable<int> BasaisaraiJanePradesh { get; set; }
        public Nullable<int> BasaisaraiJaneJilla { get; set; }
        public Nullable<int> BasaisaraiJanePalika { get; set; }
        public Nullable<int> BasaisaraiJaneWardNo { get; set; }
        public string BasaisaraiJaneGharNo { get; set; }
        public string BasaisaraiJaneGaunTole { get; set; }
    
        public virtual tblPanjika tblPanjika { get; set; }
        public virtual ICollection<tblBasaisaraiDartaInformant> tblBasaisaraiDartaInformants { get; set; }
        public virtual ICollection<tblBasaisaraiPersonalDetail> tblBasaisaraiPersonalDetails { get; set; }
    }
}
