//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJanmaDartaInformant
    {
        public int NewBornInformantId { get; set; }
        public int NewbornId { get; set; }
        public string InfNaamThar { get; set; }
        public string InfFullName { get; set; }
        public int InfRelationToNewBorn { get; set; }
        public Nullable<int> InfState { get; set; }
        public Nullable<int> InfDistrict { get; set; }
        public Nullable<int> InfPalika { get; set; }
        public Nullable<int> InfWardNo { get; set; }
        public string InfGaunTole { get; set; }
        public string InfGharNo { get; set; }
        public string InfNagariktaPraPaNo { get; set; }
        public string InfNagariktaIssueDate { get; set; }
        public Nullable<int> InfNagariktaIssueDistrict { get; set; }
        public string InfPassportNo_Desh { get; set; }
        public string Miti { get; set; }
    
        public virtual tblJanmaDarta tblJanmaDarta { get; set; }
    }
}
