//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJaggaCharKillaBibaran
    {
        public int JaggaCharKillaBibaranId { get; set; }
        public int JaggaDhaniBibaranId { get; set; }
        public int JaggaThaunBibaranId { get; set; }
    
        public virtual tblJaggaThaunBibaran tblJaggaThaunBibaran { get; set; }
    }
}
