//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJaggaDhaniBibaran
    {
        public int JaggaDhaniBibaranId { get; set; }
        public string JaggaDhaniName { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> PalikaId { get; set; }
        public Nullable<int> WardNo { get; set; }
        public string FatherName { get; set; }
        public string GrandfatherName { get; set; }
        public string CitizenshipNo { get; set; }
        public Nullable<System.DateTime> CtznIssueDate { get; set; }
        public Nullable<int> CtznIssueDistrict { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public int SubmitOfficeId { get; set; }
        public int StatusId { get; set; }
        public int FiscalYearId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
