//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMrityuDartaPersonalDetail
    {
        public int NewDeathDetailsId { get; set; }
        public int NewDeathId { get; set; }
        public Nullable<int> JanmaDartaNo { get; set; }
        public string JanmaMiti { get; set; }
        public string JanmaDate { get; set; }
        public Nullable<int> JanmaPradesh { get; set; }
        public Nullable<int> JanmaJilla { get; set; }
        public Nullable<int> JanmaPalika { get; set; }
        public Nullable<int> JanmaWardNo { get; set; }
        public string JanmaGaunTole { get; set; }
        public string JanmaGharNo { get; set; }
        public string NagariktaPraPaNo { get; set; }
        public string NagariktaIsssueDate { get; set; }
        public Nullable<int> NagariktaIssueDistrict { get; set; }
        public string PassportNo_Desh { get; set; }
        public Nullable<int> ShikshaSthar { get; set; }
        public string MatriBhasa { get; set; }
        public string Dharma { get; set; }
        public string JaatJaati { get; set; }
        public string BajekoNaam { get; set; }
        public string Grandfather { get; set; }
        public string BabuNaam { get; set; }
        public string FatherName { get; set; }
        public string AamaNaam { get; set; }
        public string MotherName { get; set; }
        public Nullable<bool> MaritalStatus { get; set; }
        public string SpouseNaam { get; set; }
        public string SpouseName { get; set; }
        public string MrityuKaran { get; set; }
    
        public virtual tblMrityuDarta tblMrityuDarta { get; set; }
    }
}
