//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPanjika
    {
        public tblPanjika()
        {
            this.tblBasaisaraiDartas = new HashSet<tblBasaisaraiDarta>();
            this.tblJanmaDartas = new HashSet<tblJanmaDarta>();
            this.tblMrityuDartas = new HashSet<tblMrityuDarta>();
            this.tblVivahDartas = new HashSet<tblVivahDarta>();
            this.tblDivorceDartas = new HashSet<tblDivorceDarta>();
        }
    
        public int PanjikaId { get; set; }
        public Nullable<int> PanjiState { get; set; }
        public Nullable<int> PanjiDistrict { get; set; }
        public Nullable<int> PanjiPalika { get; set; }
        public Nullable<int> PanjiWardNo { get; set; }
        public string PanjiNaamThar { get; set; }
        public string PanjiFullName { get; set; }
        public int Panji_INVId { get; set; }
        public Nullable<int> FiscalYear { get; set; }
        public Nullable<int> WorkOffice { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public string FaramDartaMiti { get; set; }
        public string FaramDartaDate { get; set; }
        public string PariwarLagatNo { get; set; }
        public int SifarisType { get; set; }
        public Nullable<int> JanmaDartaFaramNo { get; set; }
        public Nullable<int> MrityuDartaFaramNo { get; set; }
        public Nullable<int> VivahDartaFaramNo { get; set; }
        public Nullable<int> MigrationDartaFaramNo { get; set; }
        public Nullable<int> DivorceDartaFaramNo { get; set; }
    
        public virtual ICollection<tblBasaisaraiDarta> tblBasaisaraiDartas { get; set; }
        public virtual ICollection<tblJanmaDarta> tblJanmaDartas { get; set; }
        public virtual ICollection<tblMrityuDarta> tblMrityuDartas { get; set; }
        public virtual ICollection<tblVivahDarta> tblVivahDartas { get; set; }
        public virtual ICollection<tblDivorceDarta> tblDivorceDartas { get; set; }
    }
}
