//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public tblState()
        {
            this.tblDistricts = new HashSet<tblDistrict>();
        }
    
        public int StateId { get; set; }
        public Nullable<int> StateId_val { get; set; }
        public string StateName { get; set; }
        public string StateName_Nep { get; set; }
    
        public virtual ICollection<tblDistrict> tblDistricts { get; set; }
        public virtual tblState tblState1 { get; set; }
        public virtual tblState tblState2 { get; set; }
    }
}
