//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShakha
    {
        public int ShakhaId { get; set; }
        public string ShakhaName { get; set; }
        public Nullable<int> WorkOfficeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblWorkOffice tblWorkOffice { get; set; }
    }
}
