//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShreni
    {
        public tblShreni()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblPadhas = new HashSet<tblPadha>();
        }
    
        public int ShreniId { get; set; }
        public string ShreniName { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public int ShreniScheduleId { get; set; }
    
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        public virtual ICollection<tblPadha> tblPadhas { get; set; }
    }
}
