//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVivahBrideDetail
    {
        public int NewMarriageBrideDetailsId { get; set; }
        public int NewMarriageId { get; set; }
        public string NaamThar { get; set; }
        public string FullName { get; set; }
        public string JanmaMiti { get; set; }
        public string JaatJati { get; set; }
        public Nullable<bool> MaritalStatus { get; set; }
        public Nullable<int> ShikshaSthar { get; set; }
        public Nullable<int> Pesha { get; set; }
        public string Dharma { get; set; }
        public string MatriBhasa { get; set; }
        public Nullable<int> PermaState { get; set; }
        public Nullable<int> PermaDistrict { get; set; }
        public Nullable<int> PermaPalika { get; set; }
        public Nullable<int> PermaWardNo { get; set; }
        public string GaunTole { get; set; }
        public string GharNo { get; set; }
        public string JanmaDesh { get; set; }
        public string NagariktaLiyekoDesh { get; set; }
        public string NagariktaPraPaNo { get; set; }
        public string NagariktaIssueDate { get; set; }
        public Nullable<int> NagariktaIsssueDistrict { get; set; }
        public string PassportNo_Desh { get; set; }
        public string BideshThegana { get; set; }
        public string ForeignThegana { get; set; }
        public string BajekoNaam { get; set; }
        public string Grandfather { get; set; }
        public string BabukoNaam { get; set; }
        public string FatherName { get; set; }
        public string AamakoNaam { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> VivahGardaAge { get; set; }
    
        public virtual tblVivahDarta tblVivahDarta { get; set; }
    }
}
