//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifaris
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOffice
    {
        public tblWorkOffice()
        {
            this.tblDepartments = new HashSet<tblDepartment>();
            this.tblShakhas = new HashSet<tblShakha>();
        }
    
        public int WorkOfficeId { get; set; }
        public string Title { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string WorkOfficeAddress { get; set; }
    
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
        public virtual tblDistrict tblDistrict { get; set; }
        public virtual ICollection<tblShakha> tblShakhas { get; set; }
    }
}
