//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen_GharJagga_Info
    {
        public int Citizen_gharjaga_Id { get; set; }
        public Nullable<int> Citizen_Id { get; set; }
        public Nullable<int> NumberOfHouse { get; set; }
        public string Area { get; set; }
        public string Kitta_No { get; set; }
        public string East { get; set; }
        public string West { get; set; }
        public string North { get; set; }
        public string South { get; set; }
    
        public virtual Citizen_Info Citizen_Info { get; set; }
    }
}
