//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citizen_Info()
        {
            this.Citizen_GharJagga_Info = new HashSet<Citizen_GharJagga_Info>();
            this.JaagaTarfas = new HashSet<JaagaTarfa>();
            this.Karlayatarfas = new HashSet<Karlayatarfa>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Citizen_id { get; set; }
        public string Citizenship_No { get; set; }
        public string Address { get; set; }
        public Nullable<int> District_Id { get; set; }
        public Nullable<int> Zone_Id { get; set; }
        public Nullable<int> Mun_Ward { get; set; }
        public Nullable<int> Sabik_Ward { get; set; }
        public string Father_Husband_Name { get; set; }
        public string GrandFatherName { get; set; }
        public string CitizenShip_Date { get; set; }
        public Nullable<int> CitizinShip_Zone { get; set; }
        public Nullable<int> DeparmentId { get; set; }
        public string CitizenName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citizen_GharJagga_Info> Citizen_GharJagga_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JaagaTarfa> JaagaTarfas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karlayatarfa> Karlayatarfas { get; set; }
        public virtual Department Department { get; set; }
    }
}
