//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class fiscal_year
    {
        public int FiscalId { get; set; }
        public string Nanem { get; set; }
        public string StartDate { get; set; }
        public Nullable<System.DateTime> StartDateAd { get; set; }
        public string EndDate { get; set; }
        public Nullable<System.DateTime> EndDateAd { get; set; }
        public Nullable<int> PreviousYear { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatteBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
