//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karlayatarfa
    {
        public int Karlayatarfa_id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Date { get; set; }
        public string KardartaFullName { get; set; }
        public Nullable<int> citizen_ID { get; set; }
    
        public virtual Citizen_Info Citizen_Info { get; set; }
    }
}
