//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateDetail
    {
        public long Id { get; set; }
        public long StateId { get; set; }
        public string Capital { get; set; }
        public string ChiefMinister { get; set; }
        public string PDensity { get; set; }
        public string Governer { get; set; }
        public string Population { get; set; }
        public string Area { get; set; }
        public string Website { get; set; }
        public Nullable<int> TotalDist { get; set; }
    
        public virtual State State { get; set; }
    }
}
