//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBasaisaraiPersonalDetail
    {
        public int BasaisaraiDetailsId { get; set; }
        public int NewMigrationId { get; set; }
        public Nullable<int> JanmaDartaNo { get; set; }
        public string NaamThar { get; set; }
        public string FullName { get; set; }
        public string JanmaMiti { get; set; }
        public string JanmaDate { get; set; }
        public Nullable<int> JanmaPradesh { get; set; }
        public Nullable<int> JanmaJilla { get; set; }
        public Nullable<int> JanmaPalika { get; set; }
        public Nullable<int> JanmaWardNo { get; set; }
        public Nullable<int> Gender { get; set; }
        public string NagariktaPraPaNo { get; set; }
        public string NagaritaIssueDate { get; set; }
        public Nullable<int> NagariktaIssueDistrict { get; set; }
        public string AnyRecords { get; set; }
        public Nullable<int> RelationTo { get; set; }
    
        public virtual tblBasaisaraiDarta tblBasaisaraiDarta { get; set; }
    }
}
