//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDivorceeWifeDetail
    {
        public int DivorceeWifeId { get; set; }
        public int DivorceId { get; set; }
        public string NaamThar { get; set; }
        public string FullName { get; set; }
        public string JanmaMiti { get; set; }
        public string JanmaDartaNo { get; set; }
        public string JanmaDesh { get; set; }
        public string NagariktaPraPaNo { get; set; }
        public string NagariktaIssueDate { get; set; }
        public Nullable<int> NagariktaIssueDistrict { get; set; }
        public string BideshPassport_Desh { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> Palika { get; set; }
        public Nullable<int> WardNo { get; set; }
        public string JaatJati { get; set; }
        public Nullable<int> ShikshaSthar { get; set; }
        public string Dharma { get; set; }
        public string MatriBhasa { get; set; }
        public string BaajekoNaamThar { get; set; }
        public string BaajekoFullName { get; set; }
        public string BabukoNaamThar { get; set; }
        public string BabukoFullName { get; set; }
        public string AamakoNaamThar { get; set; }
        public string AamakoFullName { get; set; }
        public Nullable<int> ChildLivingWith { get; set; }
        public Nullable<int> SonLivingWith { get; set; }
        public Nullable<int> DaughterLivingWith { get; set; }
    
        public virtual tblDivorceDarta tblDivorceDarta { get; set; }
    }
}
