//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDivorceDarta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDivorceDarta()
        {
            this.tblDivorceDartaInformants = new HashSet<tblDivorceDartaInformant>();
            this.tblDivorceeHusbandDetails = new HashSet<tblDivorceeHusbandDetail>();
            this.tblDivorceeWifeDetails = new HashSet<tblDivorceeWifeDetail>();
        }
    
        public int DivorceId { get; set; }
        public int PanjiId { get; set; }
        public Nullable<int> CourtType { get; set; }
        public Nullable<int> District { get; set; }
        public string NirnayaNo { get; set; }
        public string NinayaMiti { get; set; }
        public string VivahDartaNo { get; set; }
    
        public virtual tblPanjika tblPanjika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDivorceDartaInformant> tblDivorceDartaInformants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDivorceeHusbandDetail> tblDivorceeHusbandDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDivorceeWifeDetail> tblDivorceeWifeDetails { get; set; }
    }
}
