//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblUserProfiles = new HashSet<tblUserProfile>();
        }
    
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public string EmployeeContact { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public int WorkOfficeId { get; set; }
        public Nullable<int> ShreniId { get; set; }
        public Nullable<int> PadhaId { get; set; }
        public int UserTypeId { get; set; }
        public bool Status { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<int> INVId { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
    
        public virtual tblUserType tblUserType { get; set; }
        public virtual tblPadha tblPadha { get; set; }
        public virtual tblShreni tblShreni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserProfile> tblUserProfiles { get; set; }
    }
}
