//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJanmaDartaMotherDetail
    {
        public int NewBornMotherId { get; set; }
        public int NewbornId { get; set; }
        public string NaamThar { get; set; }
        public string FullName { get; set; }
        public Nullable<int> PermaState { get; set; }
        public Nullable<int> PermaDistrict { get; set; }
        public Nullable<int> PermaPalika { get; set; }
        public Nullable<int> PermaWardNo { get; set; }
        public string GaunTole { get; set; }
        public string GharNo { get; set; }
        public Nullable<int> SisuJanmidakoUmer { get; set; }
        public string JanmaDesh { get; set; }
        public string NagariktaLiyekoDesh { get; set; }
        public string NagariktaPraPaNo { get; set; }
        public string NagariktaIssueDate { get; set; }
        public Nullable<int> NagariktaIssueDistrict { get; set; }
        public string PassportNo_Desh { get; set; }
        public Nullable<int> ShikshaSthar { get; set; }
        public Nullable<int> Pesha { get; set; }
        public string Dharma { get; set; }
        public string MatriBhasa { get; set; }
    
        public virtual tblJanmaDarta tblJanmaDarta { get; set; }
    }
}
