//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMrityuDarta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMrityuDarta()
        {
            this.tblMrityuDartaInformants = new HashSet<tblMrityuDartaInformant>();
            this.tblMrityuDartaPersonalDetails = new HashSet<tblMrityuDartaPersonalDetail>();
        }
    
        public int NewDeathId { get; set; }
        public int PanjiId { get; set; }
        public string NaamThar { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Gender { get; set; }
        public string MrityuMiti { get; set; }
        public string MrityuDate { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> MrityuPradesh { get; set; }
        public Nullable<int> MrityuJilla { get; set; }
        public Nullable<int> MrityuPalika { get; set; }
        public Nullable<int> MrityuWardNo { get; set; }
        public string MrityuGaunTole { get; set; }
        public string MrityuGharNo { get; set; }
        public Nullable<int> MrityuBhayekoSthaan { get; set; }
    
        public virtual tblPanjika tblPanjika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMrityuDartaInformant> tblMrityuDartaInformants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMrityuDartaPersonalDetail> tblMrityuDartaPersonalDetails { get; set; }
    }
}
