//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNataPramanit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNataPramanit()
        {
            this.tblNataPersonalDetails = new HashSet<tblNataPersonalDetail>();
        }
    
        public int NewNataId { get; set; }
        public string NaamThar { get; set; }
        public string FullName { get; set; }
        public int Gender { get; set; }
        public Nullable<int> PermaState { get; set; }
        public Nullable<int> PermaDistrict { get; set; }
        public Nullable<int> PermaPalika { get; set; }
        public Nullable<int> PermaWard { get; set; }
        public string NagariktaPraPaNo { get; set; }
        public string NagariktaIssueDate { get; set; }
        public Nullable<int> NagariktaIssueDistrict { get; set; }
        public int NataPramanitFaramNo { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public Nullable<int> WorkOffice { get; set; }
        public Nullable<int> FiscalYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNataPersonalDetail> tblNataPersonalDetails { get; set; }
    }
}
