//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNataPersonalDetail
    {
        public int NataPersonId { get; set; }
        public int NataId { get; set; }
        public string NaamThar { get; set; }
        public string FullName { get; set; }
        public Nullable<int> RelatonTo { get; set; }
    
        public virtual tblNataPramanit tblNataPramanit { get; set; }
    }
}
