//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNabalakRelativeDetail
    {
        public int NabalkRelativeInfoId { get; set; }
        public int NabalakId { get; set; }
        public string BabukoNaamThar { get; set; }
        public string BabukoFullName { get; set; }
        public string AamakoNaamThar { get; set; }
        public string AamakoFullName { get; set; }
        public string SamrakshakNaamThar { get; set; }
        public string GuardianFullName { get; set; }
    
        public virtual tblNabalakSifari tblNabalakSifari { get; set; }
    }
}
