//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNagariktaRelativeDetail
    {
        public int NagariktaRelativeInfoId { get; set; }
        public int NagariktaId { get; set; }
        public string BabukoNaamThar { get; set; }
        public string BabukoFullName { get; set; }
        public string BabuNagariktaNo { get; set; }
        public string BabuNagariktaIssueDate { get; set; }
        public Nullable<int> BabuNagariktaIssueDistrict { get; set; }
        public string AamakoNaamThar { get; set; }
        public string AamakoFullName { get; set; }
        public string AamaNagariktaNo { get; set; }
        public string AamaNagariktaIssueDate { get; set; }
        public Nullable<int> AamaNagariktaIssueDistrict { get; set; }
        public string PatikoNaamThar { get; set; }
        public string PatikoFullName { get; set; }
        public string PatiNagariktaNo { get; set; }
        public string PatiNagariktaIssueDate { get; set; }
        public Nullable<int> PatiNagariktaIssueDistrict { get; set; }
    
        public virtual tblNagariktaSifari tblNagariktaSifari { get; set; }
    }
}
