//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPalika
    {
        public int PalikaId { get; set; }
        public int PalikaId_val { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string PalikaName { get; set; }
        public string PalikaName_Nep { get; set; }
    }
}
