//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVivahDarta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVivahDarta()
        {
            this.tblVivahBrideDetails = new HashSet<tblVivahBrideDetail>();
            this.tblVivahDartaInformants = new HashSet<tblVivahDartaInformant>();
            this.tblVivahGroomDetails = new HashSet<tblVivahGroomDetail>();
        }
    
        public int NewMarriageId { get; set; }
        public int PanjiId { get; set; }
        public Nullable<int> VivahKisim { get; set; }
        public string VivahBhayekoMiti { get; set; }
        public string VivahBhayekoDate { get; set; }
        public Nullable<int> VivahPradesh { get; set; }
        public Nullable<int> VivahJilla { get; set; }
        public Nullable<int> VivahPalika { get; set; }
        public Nullable<int> VivahWardNo { get; set; }
        public string VivahGaunTole { get; set; }
        public string VivahGharNo { get; set; }
        public string VivahBidesh { get; set; }
        public string VivahForeign { get; set; }
    
        public virtual tblPanjika tblPanjika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVivahBrideDetail> tblVivahBrideDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVivahDartaInformant> tblVivahDartaInformants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVivahGroomDetail> tblVivahGroomDetails { get; set; }
    }
}
