//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVivahKisim
    {
        public int VivahKisimId { get; set; }
        public string VivahKisim { get; set; }
        public string VivahKisim_Nep { get; set; }
    }
}
