//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WardDetail
    {
        public long Id { get; set; }
        public Nullable<long> WardId { get; set; }
        public string Area { get; set; }
        public string Density { get; set; }
        public string Popullation { get; set; }
    
        public virtual Ward Ward { get; set; }
    }
}
